=== sebafermanelli/event-management/src/main/resources/xml/employee.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="employeeType">
        <xs:sequence>
            <xs:element name="cuil" type="xs:string"/>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="address" type="xs:string"/>
            <xs:element name="phone" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
            <xs:element name="salary" type="xs:decimal"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:element name="employee" type="employeeType"/>
</xs:schema>

=== sebafermanelli/event-management/src/main/resources/xml/employee.xml
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="employee.xsd">
    <cuil>20428378825</cuil>
    <firstName>Juan</firstName>
    <lastName>Fernandez</lastName>
    <address>San Juan 5203, C1425 CABA</address>
    <phone>+5493412834729</phone>
    <email>juan.rodriguez@gmail.com</email>
    <salary>340000</salary>
</employee>
