=== sebafermanelli/event-management/src/main/resources/xml/presentation.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="employeeType">
        <xs:all>
            <xs:element name="cuil" type="xs:string"/>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="address" type="xs:string"/>
            <xs:element name="phone" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
            <xs:element name="salary" type="xs:decimal"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="employeesType">
        <xs:sequence>
            <xs:element name="employee" type="employeeType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="eventType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="theme" type="xs:string"/>
            <xs:element name="baseTicketPrice" type="xs:long"/>
            <xs:element name="startDate" type="xs:string"/>
            <xs:element name="endDate" type="xs:string"/>
            <xs:element name="address" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="employees" type="employeesType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="roomType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="surface" type="xs:long"/>
            <xs:element name="capacity" type="xs:integer"/>
            <xs:element name="status" type="xs:string"/>
            <xs:element name="event" type="eventType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="presenterType">
        <xs:sequence>
            <xs:element name="cuil" type="xs:string"/>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="address" type="xs:string"/>
            <xs:element name="phone" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
            <xs:element name="specialization" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="presentationType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="startDateTime" type="xs:string"/>
            <xs:element name="endDateTime" type="xs:string"/>
            <xs:element name="ticketPrice" type="xs:long"/>
            <xs:element name="room" type="roomType"/>
            <xs:element name="presenter" type="presenterType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="presentation" type="presentationType"/>
</xs:schema>

=== sebafermanelli/event-management/src/main/resources/xml/presentation.xml
<?xml version="1.0" encoding="UTF-8"?>
<presentation id="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="presentation.xsd">
    <name>Motorcycles on the road</name>
    <description>Join us for an exhilarating exploration at the Motorcycles on the Road conference, where enthusiasts,
        industry experts, and visionaries come together to delve into the dynamic world of two-wheel adventures
    </description>
    <startDateTime>2023-12-20 12:00:00</startDateTime>
    <endDateTime>2023-12-20 13:00:00</endDateTime>
    <ticketPrice>1000</ticketPrice>
    <room id="2">
        <name>North room</name>
        <surface>200</surface>
        <capacity>180</capacity>
        <status>Available</status>
        <event id="1">
            <name>Salon Moto 2023</name>
            <theme>Motorcycles Exposition</theme>
            <baseTicketPrice>3500</baseTicketPrice>
            <startDate>2023-12-19 09:00:00</startDate>
            <endDate>2023-12-22 22:00:00</endDate>
            <address>Av. Sarmiento 2704, C1425 CABA</address>
            <description>Enjoy live music, delicious food, and connect with like-minded individuals who share your
                passion for the open road.
            </description>
            <employees>
                <employee id="1">
                    <cuil>20428378825</cuil>
                    <firstName>Juan</firstName>
                    <lastName>Fernandez</lastName>
                    <address>San Juan 5203, C1425 CABA</address>
                    <phone>+5493412834729</phone>
                    <email>juan.rodriguez@gmail.com</email>
                    <salary>340000</salary>
                </employee>
            </employees>
        </event>
    </room>
    <presenter id="1">
        <cuil>20328729935</cuil>
        <firstName>Gerardo</firstName>
        <lastName>Perez</lastName>
        <address>Av. Santa Fe 3823, C1425 CABA</address>
        <phone>+5494728972982</phone>
        <email>gerardo.perez@gmail.com</email>
        <specialization>Mechanical Engineer</specialization>
    </presenter>
</presentation>
