=== sebafermanelli/event-management/src/main/resources/xml/stand.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="employeeType">
        <xs:all>
            <xs:element name="cuil" type="xs:string"/>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="address" type="xs:string"/>
            <xs:element name="phone" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
            <xs:element name="salary" type="xs:decimal"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="employeesType">
        <xs:sequence>
            <xs:element name="employee" type="employeeType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="eventType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="theme" type="xs:string"/>
            <xs:element name="baseTicketPrice" type="xs:long"/>
            <xs:element name="startDate" type="xs:dateTime"/>
            <xs:element name="endDate" type="xs:dateTime"/>
            <xs:element name="address" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="employees" type="employeesType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="roomType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="surface" type="xs:long"/>
            <xs:element name="capacity" type="xs:integer"/>
            <xs:element name="status" type="xs:string"/>
            <xs:element name="event" type="eventType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="clientType">
        <xs:sequence>
            <xs:element name="cuit" type="xs:string"/>
            <xs:element name="businessName" type="xs:string"/>
            <xs:element name="address" type="xs:string"/>
            <xs:element name="phone" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="standType">
        <xs:sequence>
            <xs:element name="price" type="xs:long"/>
            <xs:element name="room" type="roomType"/>
            <xs:element name="client" type="clientType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="stand" type="standType"/>
</xs:schema>

=== sebafermanelli/event-management/src/main/resources/xml/stand.xml
<stand xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="stand.xsd">
    <price>480000</price>
    <room id="1">
        <name>Main hall</name>
        <surface>1500</surface>
        <capacity>1200</capacity>
        <status>Available</status>
        <event id="1">
            <name>Salon Moto 2023</name>
            <theme>Motorcycles Exposition</theme>
            <baseTicketPrice>3500</baseTicketPrice>
            <startDate>2023-12-19 09:00:00</startDate>
            <endDate>2023-12-22 22:00:00</endDate>
            <address>Av. Sarmiento 2704, C1425 CABA</address>
            <description>Enjoy live music, delicious food, and connect with like-minded individuals who share your
                passion for
                the open road.
            </description>
            <employees>
                <employee id="1">
                    <cuil>20428378825</cuil>
                    <firstName>Juan</firstName>
                    <lastName>Fernandez</lastName>
                    <address>San Juan 5203, C1425 CABA</address>
                    <phone>+5493412834729</phone>
                    <email>juan.rodriguez@gmail.com</email>
                    <salary>340000</salary>
                </employee>
            </employees>
        </event>
    </room>
    <client id="1">
        <cuit>20224448235</cuit>
        <businessName>Ducati</businessName>
        <address>La Madrid 105, C1425 CABA</address>
        <phone>+5492384927738</phone>
        <email>ducati@gmail.com</email>
    </client>
</stand>
